---
- name: Roda todos os playbooks
  hosts: localhost

- name: Chama o playbook de prerequisitos
  import_playbook: prereqs.yml

- name: Chama o playbook do docker
  import_playbook: docker.yml

- name: Chama o playbook de deploy
  import_playbook: deploy.yml
