---
# tasks file for docker
- name: Garante que um container do apache esteja rodando
  docker_container:
    name: "{{item}}"
    image: httpd
    volumes:
      - "/srv/{{item}}:/usr/local/apache2/htdocs/"
  with_items:
    - blue
    - green

- name: Registra o ip dos containers
  register: "{{item}}_result"
  shell: "docker inspect --format '{''{ .NetworkSettings.IPAddress }''}' {{item}}"
  ignore_errors: True
  with_items:
    - blue
    - green
