---
# tasks file for pacotes
- name: Instala os pacotes
  package:
    name: "{{item}}"
    state: present
  with_items:
    - docker-ce
    - nginx
    - python-pip

- name: Instala o docker-py
  pip:
    name: docker-py
